### ISSUE TITLE
treetable supported？

### ISSUE THREAD

**Issue by ddkwork** [cenfun/lithops-ui#1]

**Comment by cenfun** [comment]
see this one 
https://github.com/cenfun/turbogrid
and here is custom element demo
https://cenfun.github.io/turbogrid/custom-element.html

**Comment by ddkwork** [comment]
> see this one 
> https://github.com/cenfun/turbogrid
> and here is custom element demo
> https://cenfun.github.io/turbogrid/custom-element.html
> 

Wow, very good. And how to replace expand ico as this:

![1698197943724.png](https://github.com/cenfun/lithops-ui/assets/19886504/7ba809fd-3b2a-4979-889f-28962804b738)

https://github.com/richardwilkes/gcs

**Comment by cenfun** [comment]
Actually the column of icon and label was renderered with the `tree` formatter, you can overwriting it like following
```
grid.setFormatter({
    tree: function(value, rowItem, columnItem, cellNode) {
        return value;
    }
});
```
see APIs https://cenfun.github.io/turbogrid/api.html#setFormatter
default implementations: 
https://github.com/cenfun/turbogrid/blob/main/src/config/default-formatters.js#L58-L60
https://github.com/cenfun/turbogrid/blob/main/src/grid/formatter.js#L95

**Comment by ddkwork** [comment]
> Actually the column of icon and label was renderered with the `tree` formatter, you can overwriting it like following
> ```
> grid.setFormatter({
>     tree: function(value, rowItem, columnItem, cellNode) {
>         return value;
>     }
> });
> ```
> see APIs https://cenfun.github.io/turbogrid/api.html#setFormatter
> default implementations: 
> https://github.com/cenfun/turbogrid/blob/main/src/config/default-formatters.js#L58-L60
> https://github.com/cenfun/turbogrid/blob/main/src/grid/formatter.js#L95

Nice, i will try to use wails and vite call this rep and then build it as apk, thx you very much.
